package nm

import (
	"strings"
	"testing"
)

var validLines = []string{
	`                  0 U`,
	`                  0 U <autogenerated>`,
	`   67565         85 ? go:constinfo.storj.io/picobuf`,
	`   9299e         11 R gclocals·+1O0nV3p1V/MtobnbK5tTA==`,
	`           16781312 U _mmap`,
	`           16781312 U _mmap`,
	`           16781312 U _munmap`,
	`           16781312 U _notify_is_valid_token`,
	`           16781312 U _open`,
	` 10d8fe0          8 R $f64.4024000000000000`,
	` 10d8fe8          8 R $f64.403a000000000000`,
	`115d4a0        256 D time.utcLoc`,
	`1091ca0        192 T type:.eq.[2]interface {}`,
	`1060160        160 T type:.eq.[2]runtime.Frame`,
	`1001fa0        256 T type:.eq.[6]internal/cpu.option`,
	`       0          0 _ go.go`,
	`    5b07         79 ? .file`,
}

func TestParseLineFields(t *testing.T) {
	tests := []struct {
		line       string
		path, name string
	}{
		{`115d4a0        256 D time.utcLoc`, "time", "utcLoc"},
		{`10018d8f0        800 T encoding/json/v2.(*typedArshalers[go.shape.struct { encoding/json/jsontext.s }]).lookup`, "encoding/json/v2", "(*typedArshalers[go.shape.struct { encoding/json/jsontext.s }]).lookup"},
		{`10018dc10        176 T cmp.Or[go.shape.interface { Error() string }]`, "cmp", "Or[go.shape.interface { Error() string }]"},
		{`1000 16 T reflect.TypeAssert[encoding/json.Marshaler]`, "reflect", "TypeAssert[encoding/json.Marshaler]"},
		{`           16781312 U _mmap`, "", "_mmap"},
		{`                  0 U`, "", ""},
	}
	for _, test := range tests {
		sym, err := parseLine(test.line)
		if err != nil {
			t.Fatalf("%q: %v", test.line, err)
		}
		if got := strings.Join(sym.Path, "/"); got != test.path || sym.Name != test.name {
			t.Errorf("%q:\n got %q %q\nwant %q %q", test.line, got, sym.Name, test.path, test.name)
		}
	}
}

func TestParseLine(t *testing.T) {
	for _, line := range validLines {
		_, err := parseLine(line)
		t.Log(strings.Fields(line))
		if err != nil {
			t.Errorf("%q parsing failed: %v", line, err)
		}
	}
}
